name = "Porcupine"
uuid = "3b53a3d7-3f34-4bba-8df2-4717a8b1e972"
authors = ["Paul Shen <pxshen@alumni.stanford.edu>"]
version = "1.0.43"

[deps]
ArrayPadding = "fe5ef43c-4912-423d-9170-4bd5cb6a013a"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Format = "1fa38f19-a742-5d3f-a2b9-30dd87b9d5f8"
Functors = "d9f16b24-f501-4c13-a1f2-28368ffc5196"
GPUArraysCore = "46192b85-c4d5-4398-a991-12ede77f4527"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[weakdeps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[extensions]
CUDAExt = "CUDA"
ZygoteExt = "Zygote"

[compat]
ArrayPadding = "1"
CUDA = "5,6,7,8"
ChainRulesCore = "1"
DataStructures = "0.18,0.19,0.20,1"
Format = "1,2,3"
Functors = "0.1,0.2,0.3,0.4,0.5,0.6,1"
GPUArraysCore = "0.2,0.3,0.4,1"
JSON = "0.21,0.22,0.23,0.24,0.25,0.26,0.27,0.28,0.29,0.30,1,2"
LinearAlgebra = "1"
StaticArrays = "1.9.15"
Statistics = "1"
UnPack = "1"
Zygote = "0.6,0.7,0.8,1"
julia = "1"
